spring.application.name=usuarios-service
server.port=8081

# =========================
# BASE DE DATOS
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/piedrazul_usuarios
spring.datasource.username=piedrazul
spring.datasource.password=db_piedrazul

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# COMUNICACI?N CON MICROSERVICIOS
# =========================
personas.service.url=http://localhost:8082