# Nombre del microservicio
spring.application.name=personas-service

# =========================
# BASE DE DATOS
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/piedrazul_personas
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
