spring.application.name=personas-service
server.port=8082

# =========================
# BASE DE DATOS
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/piedrazul_personas
spring.datasource.username=piedrazul
spring.datasource.password=db_piedrazul

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
